customhost = "employee.cyzhoxynlt5j.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "lowcheeseng-employee"
customregion = "us-east-1"
